# Migration Phase 4: `FeatureStore` for the new tabular-derivatives schema

`src/neuroalign/data/preprocessing/feature_store.py` is rewritten for the
`TabularDerivativesLoader` long-format outputs (Phases 2-3):

- **Long format**: `anatomical.parquet` (Schaefer2018N400n7 + Tian2020S2,
  cortex+subcortex concatenated) and `diffusion/<software>.parquet` (one
  file per software, e.g. `DSIStudio.parquet`, `AMICONODDI.parquet`).
- **`ANATOMICAL_METRICS`** / **`DIFFUSION_METRICS`** updated to the new
  column sets (`thickness_mean_mm`, `gray_matter_volume_mm3`, ...,
  `mean`, `robust_mean`, `percentile_5`, ...).
- **Wide format**: `anat_<metric>.parquet` (one per anatomical metric) and
  `<software>_<model>_<param>[_<desc>]_<metric>.parquet` (one per diffusion
  combination/metric), pivoted on `label` (region).
- **`save_tiv()`** now just extracts `tiv_mm3` straight from the anatomical
  long format - no MATLAB/CAT12 step.
- All join keys are now `uid` + `session_id` (`META_COLS`), matching
  `BehavioralLoader` and `TabularDerivativesLoader`.

This notebook builds a small demo store under `data/processed/` (gitignored)
from a 5-session sample.

In [1]:
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv(Path.cwd().parent / ".env")

from neuroalign.data.loaders import BehavioralLoader, TabularDerivativesLoader
from neuroalign.data.preprocessing.feature_store import FeatureStore

beh = BehavioralLoader(os.environ["BRAINLINK_DB_PATH"])
loader = TabularDerivativesLoader(
    os.environ["TABULAR_DERIVATIVES_ROOT"],
    atlas_name=os.environ["ATLAS_NAME"],
    anat_atlases=tuple(os.environ["ANAT_ATLASES"].split(",")),
    session_variant=os.environ["SESSION_VARIANT"],
)

store_dir = Path.cwd().parent / "data" / "processed" / "phase4_demo"
store = FeatureStore(store_dir)
print(f"store_dir={store_dir}")

store_dir=/home/galkepler/Projects/neuroalign/data/processed/phase4_demo

## 1. Load a small sample

Reuse the 5-session sample with diffusion data from Phase 3, plus the
matching anatomical data.

In [2]:
import pandas as pd

sessions = beh.get_sessions()
tabular_root = Path(os.environ["TABULAR_DERIVATIVES_ROOT"])
atlas = os.environ["ATLAS_NAME"]

found = []
for uid, sid in sessions[["uid", "session_id"]].drop_duplicates().itertuples(index=False):
    if (tabular_root / f"sub-{uid}" / f"ses-{sid}" / "dwi" / f"atlas-{atlas}").exists():
        found.append((uid, sid))
        if len(found) >= 5:
            break

sample = pd.DataFrame(found, columns=["uid", "session_id"])
sample_sessions = sessions.merge(sample, on=["uid", "session_id"])

anat = loader.load_anatomical(sample)
dwi = loader.load_diffusion(sample)
print(f"anat: {anat.shape}, dwi: {dwi.shape}, sessions: {sample_sessions.shape}")

anat: (864, 31), dwi: (123120, 33), sessions: (5, 17)

## 2. Save long format

`save_anatomical_long()` writes one `anatomical.parquet`.
`save_diffusion_long()` splits by `software` into `diffusion/<software>.parquet`.

In [3]:
anat_name = store.save_anatomical_long(anat, atlas_name=atlas)
dwi_names = store.save_diffusion_long(dwi, atlas_name=atlas)
print("anat:", anat_name)
print("dwi:", dwi_names)
print()
print("long formats:", store.list_long_formats())

anat: anatomical
dwi: ['diffusion_AMICONODDI', 'diffusion_DIPYDKI', 'diffusion_DIPYMAPMRI', 'diffusion_DSIStudio', 'diffusion_MRtrix3actHSVS']

long formats: ['anatomical', 'diffusion_AMICONODDI', 'diffusion_DIPYDKI', 'diffusion_DIPYMAPMRI', 'diffusion_DSIStudio', 'diffusion_MRtrix3actHSVS']

## 3. TIV

`save_tiv()` extracts `tiv_mm3` directly from the anatomical long format -
one row per (uid, session_id).

In [4]:
tiv_name = store.save_tiv(anat)
store.load_tiv()

       uid    session_id       tiv_mm3
0  S629697  202601111959  1.415257e+06
1  S076379  202410131245  1.500654e+06

## 4. Metadata

`save_metadata()` stores the `BehavioralLoader` session table directly
(`uid`, `session_id`, `AGE`, `sex`, `lab`, ...).

In [5]:
store.save_metadata(sample_sessions)
store.load_metadata()[["uid", "session_id", "lab", "AGE", "sex"]]

       uid    session_id   lab        AGE     sex
0  S629697  202601111959    YA  37.691992  Female
1  S667793  202601181721    YA  27.641342  Female
2  S307570  202601051400  SNBB  25.262149  Female
3  S076379  202410131245    TS  22.260000  Female
4  S105498  202601141203    YA  36.720055  Female

## 5. Generate wide features

One `anat_<metric>.parquet` per anatomical metric, one
`<software>_<model>_<param>[_<desc>]_<metric>.parquet` per diffusion
combination/metric.

In [6]:
generated = store.generate_wide_features()
print(f"{len(generated)} wide features generated")
print("anatomical:", store.list_features("anatomical")[:5], "...")
print("diffusion:", store.list_features("diffusion")[:5], "...")

1277 wide features generated
anatomical: ['anat_brain_seg_no_vent_mm3', 'anat_brain_seg_vol_mm3', 'anat_cortex_vol_mm3', 'anat_curvature_index', 'anat_folding_index'] ...
diffusion: ['AMICONODDI_noddi_direction_coverage', 'AMICONODDI_noddi_direction_cv', 'AMICONODDI_noddi_direction_excess_kurtosis', 'AMICONODDI_noddi_direction_iqr_filtered_mean', 'AMICONODDI_noddi_direction_iqr_filtered_std'] ...

## 6. Load a feature

`load_feature()` merges the wide feature with metadata (`AGE`, `sex`) and
TIV on `uid` + `session_id`.

In [7]:
ct = store.load_feature("anat_thickness_mean_mm", include_tiv=True)
print(ct.shape)
ct[["uid", "session_id", "AGE", "sex", "tiv_mm3"] + [c for c in ct.columns if c.startswith("LH_Vis")][:3]]

(2, 418)

       uid    session_id        AGE     sex       tiv_mm3
0  S076379  202410131245  22.260000  Female  1.500654e+06
1  S629697  202601111959  37.691992  Female  1.415257e+06

In [8]:
fa = store.load_feature("DSIStudio_tensor_fa_mean")
print(fa.shape)
fa[["uid", "session_id", "AGE"] + [c for c in fa.columns if c.startswith("LH_Vis")][:3]]

(5, 449)

       uid    session_id        AGE  LH_Vis_1  LH_Vis_10  LH_Vis_11
0  S076379  202410131245  22.260000  0.161196   0.196716   0.189170
1  S105498  202601141203  36.720055  0.197376   0.209543   0.201873
2  S307570  202601051400  25.262149  0.207833   0.201729   0.190115
3  S629697  202601111959  37.691992  0.192400   0.212407   0.190610
4  S667793  202601181721  27.641342  0.171997   0.173567   0.182842

## 7. Store summary

In [9]:
store.summary()

{'root_dir': '/home/galkepler/Projects/neuroalign/data/processed/phase4_demo',
 'atlas_name': 'Schaefer2018N400n7Tian2020S2',
 'n_sessions': 5,
 'n_subjects': 5,
 'long_formats': ['anatomical',
  'diffusion_AMICONODDI',
  'diffusion_DIPYDKI',
  'diffusion_DIPYMAPMRI',
  'diffusion_DSIStudio',
  'diffusion_MRtrix3actHSVS'],
 'n_wide_features': 1278,
 'anatomical_features': ['tiv',
  'anat_num_vertices',
  'anat_surface_area_mm2',
  'anat_gray_matter_volume_mm3',
  'anat_thickness_mean_mm',
  'anat_thickness_std_mm',
  'anat_mean_curvature',
  'anat_gaussian_curvature',
  'anat_folding_index',
  'anat_curvature_index',
  'anat_white_surf_area_mm2',
  'anat_brain_seg_vol_mm3',
  'anat_brain_seg_no_vent_mm3',
  'anat_cortex_vol_mm3',
  'anat_supratentorial_vol_mm3',
  'anat_num_voxels',
  'anat_volume_mm3',
  'anat_intensity_mean',
  'anat_intensity_std',
  'anat_intensity_min',
  'anat_intensity_max',
  'anat_intensity_range',
  'anat_intensity_snr',
  'anat_subcort_gray_mm3'],
 'diffusion_features': ['AMICONODDI_noddi_direction_mean',
  'AMICONODDI_noddi_direction_std',
  'AMICONODDI_noddi_direction_median',
  'AMICONODDI_noddi_direction_sum',
  'AMICONODDI_noddi_direction_cv',
  'AMICONODDI_noddi_direction_robust_mean',
  'AMICONODDI_noddi_direction_robust_std',
  'AMICONODDI_noddi_direction_robust_cv',
  'AMICONODDI_noddi_direction_mad_median',
  'AMICONODDI_noddi_direction_z_filtered_mean',
  'AMICONODDI_noddi_direction_z_filtered_std',
  'AMICONODDI_noddi_direction_iqr_filtered_mean',
  'AMICONODDI_noddi_direction_iqr_filtered_std',
  'AMICONODDI_noddi_direction_skewness',
  'AMICONODDI_noddi_direction_excess_kurtosis',
  'AMICONODDI_noddi_direction_percentile_5',
  'AMICONODDI_noddi_direction_percentile_25',
  'AMICONODDI_noddi_direction_percentile_75',
  'AMICONODDI_noddi_direction_percentile_95',
  'AMICONODDI_noddi_direction_coverage',
  'AMICONODDI_noddi_direction_volume_mm3',
  'AMICONODDI_noddi_direction_voxel_count',
  'AMICONODDI_noddi_icvf_modulated_mean',
  'AMICONODDI_noddi_icvf_modulated_std',
  'AMICONODDI_noddi_icvf_modulated_median',
  'AMICONODDI_noddi_icvf_modulated_sum',
  'AMICONODDI_noddi_icvf_modulated_cv',
  'AMICONODDI_noddi_icvf_modulated_robust_mean',
  'AMICONODDI_noddi_icvf_modulated_robust_std',
  'AMICONODDI_noddi_icvf_modulated_robust_cv',
  'AMICONODDI_noddi_icvf_modulated_mad_median',
  'AMICONODDI_noddi_icvf_modulated_z_filtered_mean',
  'AMICONODDI_noddi_icvf_modulated_z_filtered_std',
  'AMICONODDI_noddi_icvf_modulated_iqr_filtered_mean',
  'AMICONODDI_noddi_icvf_modulated_iqr_filtered_std',
  'AMICONODDI_noddi_icvf_modulated_skewness',
  'AMICONODDI_noddi_icvf_modulated_excess_kurtosis',
  'AMICONODDI_noddi_icvf_modulated_percentile_5',
  'AMICONODDI_noddi_icvf_modulated_percentile_25',
  'AMICONODDI_noddi_icvf_modulated_percentile_75',
  'AMICONODDI_noddi_icvf_modulated_percentile_95',
  'AMICONODDI_noddi_icvf_modulated_coverage',
  'AMICONODDI_noddi_icvf_modulated_volume_mm3',
  'AMICONODDI_noddi_icvf_modulated_voxel_count',
  'AMICONODDI_noddi_icvf_mean',
  'AMICONODDI_noddi_icvf_std',
  'AMICONODDI_noddi_icvf_median',
  'AMICONODDI_noddi_icvf_sum',
  'AMICONODDI_noddi_icvf_cv',
  'AMICONODDI_noddi_icvf_robust_mean',
  'AMICONODDI_noddi_icvf_robust_std',
  'AMICONODDI_noddi_icvf_robust_cv',
  'AMICONODDI_noddi_icvf_mad_median',
  'AMICONODDI_noddi_icvf_z_filtered_mean',
  'AMICONODDI_noddi_icvf_z_filtered_std',
  'AMICONODDI_noddi_icvf_iqr_filtered_mean',
  'AMICONODDI_noddi_icvf_iqr_filtered_std',
  'AMICONODDI_noddi_icvf_skewness',
  'AMICONODDI_noddi_icvf_excess_kurtosis',
  'AMICONODDI_noddi_icvf_percentile_5',
  'AMICONODDI_noddi_icvf_percentile_25',
  'AMICONODDI_noddi_icvf_percentile_75',
  'AMICONODDI_noddi_icvf_percentile_95',
  'AMICONODDI_noddi_icvf_coverage',
  'AMICONODDI_noddi_icvf_volume_mm3',
  'AMICONODDI_noddi_icvf_voxel_count',
  'AMICONODDI_noddi_isovf_mean',
  'AMICONODDI_noddi_isovf_std',
  'AMICONODDI_noddi_isovf_median',
  'AMICONODDI_noddi_isovf_sum',
  'AMICONODDI_noddi_isovf_cv',
  'AMICONODDI_noddi_isovf_robust_mean',
  'AMICONODDI_noddi_isovf_robust_std',
  'AMICONODDI_noddi_isovf_robust_cv',
  'AMICONODDI_noddi_isovf_mad_median',
  'AMICONODDI_noddi_isovf_z_filtered_mean',
  'AMICONODDI_noddi_isovf_z_filtered_std',
  'AMICONODDI_noddi_isovf_iqr_filtered_mean',
  'AMICONODDI_noddi_isovf_iqr_filtered_std',
  'AMICONODDI_noddi_isovf_skewness',
  'AMICONODDI_noddi_isovf_excess_kurtosis',
  'AMICONODDI_noddi_isovf_percentile_5',
  'AMICONODDI_noddi_isovf_percentile_25',
  'AMICONODDI_noddi_isovf_percentile_75',
  'AMICONODDI_noddi_isovf_percentile_95',
  'AMICONODDI_noddi_isovf_coverage',
  'AMICONODDI_noddi_isovf_volume_mm3',
  'AMICONODDI_noddi_isovf_voxel_count',
  'AMICONODDI_noddi_nrmse_mean',
  'AMICONODDI_noddi_nrmse_std',
  'AMICONODDI_noddi_nrmse_median',
  'AMICONODDI_noddi_nrmse_sum',
  'AMICONODDI_noddi_nrmse_cv',
  'AMICONODDI_noddi_nrmse_robust_mean',
  'AMICONODDI_noddi_nrmse_robust_std',
  'AMICONODDI_noddi_nrmse_robust_cv',
  'AMICONODDI_noddi_nrmse_mad_median',
  'AMICONODDI_noddi_nrmse_z_filtered_mean',
  'AMICONODDI_noddi_nrmse_z_filtered_std',
  'AMICONODDI_noddi_nrmse_iqr_filtered_mean',
  'AMICONODDI_noddi_nrmse_iqr_filtered_std',
  'AMICONODDI_noddi_nrmse_skewness',
  'AMICONODDI_noddi_nrmse_excess_kurtosis',
  'AMICONODDI_noddi_nrmse_percentile_5',
  'AMICONODDI_noddi_nrmse_percentile_25',
  'AMICONODDI_noddi_nrmse_percentile_75',
  'AMICONODDI_noddi_nrmse_percentile_95',
  'AMICONODDI_noddi_nrmse_coverage',
  'AMICONODDI_noddi_nrmse_volume_mm3',
  'AMICONODDI_noddi_nrmse_voxel_count',
  'AMICONODDI_noddi_od_modulated_mean',
  'AMICONODDI_noddi_od_modulated_std',
  'AMICONODDI_noddi_od_modulated_median',
  'AMICONODDI_noddi_od_modulated_sum',
  'AMICONODDI_noddi_od_modulated_cv',
  'AMICONODDI_noddi_od_modulated_robust_mean',
  'AMICONODDI_noddi_od_modulated_robust_std',
  'AMICONODDI_noddi_od_modulated_robust_cv',
  'AMICONODDI_noddi_od_modulated_mad_median',
  'AMICONODDI_noddi_od_modulated_z_filtered_mean',
  'AMICONODDI_noddi_od_modulated_z_filtered_std',
  'AMICONODDI_noddi_od_modulated_iqr_filtered_mean',
  'AMICONODDI_noddi_od_modulated_iqr_filtered_std',
  'AMICONODDI_noddi_od_modulated_skewness',
  'AMICONODDI_noddi_od_modulated_excess_kurtosis',
  'AMICONODDI_noddi_od_modulated_percentile_5',
  'AMICONODDI_noddi_od_modulated_percentile_25',
  'AMICONODDI_noddi_od_modulated_percentile_75',
  'AMICONODDI_noddi_od_modulated_percentile_95',
  'AMICONODDI_noddi_od_modulated_coverage',
  'AMICONODDI_noddi_od_modulated_volume_mm3',
  'AMICONODDI_noddi_od_modulated_voxel_count',
  'AMICONODDI_noddi_od_mean',
  'AMICONODDI_noddi_od_std',
  'AMICONODDI_noddi_od_median',
  'AMICONODDI_noddi_od_sum',
  'AMICONODDI_noddi_od_cv',
  'AMICONODDI_noddi_od_robust_mean',
  'AMICONODDI_noddi_od_robust_std',
  'AMICONODDI_noddi_od_robust_cv',
  'AMICONODDI_noddi_od_mad_median',
  'AMICONODDI_noddi_od_z_filtered_mean',
  'AMICONODDI_noddi_od_z_filtered_std',
  'AMICONODDI_noddi_od_iqr_filtered_mean',
  'AMICONODDI_noddi_od_iqr_filtered_std',
  'AMICONODDI_noddi_od_skewness',
  'AMICONODDI_noddi_od_excess_kurtosis',
  'AMICONODDI_noddi_od_percentile_5',
  'AMICONODDI_noddi_od_percentile_25',
  'AMICONODDI_noddi_od_percentile_75',
  'AMICONODDI_noddi_od_percentile_95',
  'AMICONODDI_noddi_od_coverage',
  'AMICONODDI_noddi_od_volume_mm3',
  'AMICONODDI_noddi_od_voxel_count',
  'AMICONODDI_noddi_rmse_mean',
  'AMICONODDI_noddi_rmse_std',
  'AMICONODDI_noddi_rmse_median',
  'AMICONODDI_noddi_rmse_sum',
  'AMICONODDI_noddi_rmse_cv',
  'AMICONODDI_noddi_rmse_robust_mean',
  'AMICONODDI_noddi_rmse_robust_std',
  'AMICONODDI_noddi_rmse_robust_cv',
  'AMICONODDI_noddi_rmse_mad_median',
  'AMICONODDI_noddi_rmse_z_filtered_mean',
  'AMICONODDI_noddi_rmse_z_filtered_std',
  'AMICONODDI_noddi_rmse_iqr_filtered_mean',
  'AMICONODDI_noddi_rmse_iqr_filtered_std',
  'AMICONODDI_noddi_rmse_skewness',
  'AMICONODDI_noddi_rmse_excess_kurtosis',
  'AMICONODDI_noddi_rmse_percentile_5',
  'AMICONODDI_noddi_rmse_percentile_25',
  'AMICONODDI_noddi_rmse_percentile_75',
  'AMICONODDI_noddi_rmse_percentile_95',
  'AMICONODDI_noddi_rmse_coverage',
  'AMICONODDI_noddi_rmse_volume_mm3',
  'AMICONODDI_noddi_rmse_voxel_count',
  'AMICONODDI_noddi_tf_mean',
  'AMICONODDI_noddi_tf_std',
  'AMICONODDI_noddi_tf_median',
  'AMICONODDI_noddi_tf_sum',
  'AMICONODDI_noddi_tf_cv',
  'AMICONODDI_noddi_tf_robust_mean',
  'AMICONODDI_noddi_tf_robust_std',
  'AMICONODDI_noddi_tf_robust_cv',
  'AMICONODDI_noddi_tf_mad_median',
  'AMICONODDI_noddi_tf_z_filtered_mean',
  'AMICONODDI_noddi_tf_z_filtered_std',
  'AMICONODDI_noddi_tf_iqr_filtered_mean',
  'AMICONODDI_noddi_tf_iqr_filtered_std',
  'AMICONODDI_noddi_tf_skewness',
  'AMICONODDI_noddi_tf_excess_kurtosis',
  'AMICONODDI_noddi_tf_percentile_5',
  'AMICONODDI_noddi_tf_percentile_25',
  'AMICONODDI_noddi_tf_percentile_75',
  'AMICONODDI_noddi_tf_percentile_95',
  'AMICONODDI_noddi_tf_coverage',
  'AMICONODDI_noddi_tf_volume_mm3',
  'AMICONODDI_noddi_tf_voxel_count',
  'DIPYDKI_dki_ad_mean',
  'DIPYDKI_dki_ad_std',
  'DIPYDKI_dki_ad_median',
  'DIPYDKI_dki_ad_sum',
  'DIPYDKI_dki_ad_cv',
  'DIPYDKI_dki_ad_robust_mean',
  'DIPYDKI_dki_ad_robust_std',
  'DIPYDKI_dki_ad_robust_cv',
  'DIPYDKI_dki_ad_mad_median',
  'DIPYDKI_dki_ad_z_filtered_mean',
  'DIPYDKI_dki_ad_z_filtered_std',
  'DIPYDKI_dki_ad_iqr_filtered_mean',
  'DIPYDKI_dki_ad_iqr_filtered_std',
  'DIPYDKI_dki_ad_skewness',
  'DIPYDKI_dki_ad_excess_kurtosis',
  'DIPYDKI_dki_ad_percentile_5',
  'DIPYDKI_dki_ad_percentile_25',
  'DIPYDKI_dki_ad_percentile_75',
  'DIPYDKI_dki_ad_percentile_95',
  'DIPYDKI_dki_ad_coverage',
  'DIPYDKI_dki_ad_volume_mm3',
  'DIPYDKI_dki_ad_voxel_count',
  'DIPYDKI_dki_ak_mean',
  'DIPYDKI_dki_ak_std',
  'DIPYDKI_dki_ak_median',
  'DIPYDKI_dki_ak_sum',
  'DIPYDKI_dki_ak_cv',
  'DIPYDKI_dki_ak_robust_mean',
  'DIPYDKI_dki_ak_robust_std',
  'DIPYDKI_dki_ak_robust_cv',
  'DIPYDKI_dki_ak_mad_median',
  'DIPYDKI_dki_ak_z_filtered_mean',
  'DIPYDKI_dki_ak_z_filtered_std',
  'DIPYDKI_dki_ak_iqr_filtered_mean',
  'DIPYDKI_dki_ak_iqr_filtered_std',
  'DIPYDKI_dki_ak_skewness',
  'DIPYDKI_dki_ak_excess_kurtosis',
  'DIPYDKI_dki_ak_percentile_5',
  'DIPYDKI_dki_ak_percentile_25',
  'DIPYDKI_dki_ak_percentile_75',
  'DIPYDKI_dki_ak_percentile_95',
  'DIPYDKI_dki_ak_coverage',
  'DIPYDKI_dki_ak_volume_mm3',
  'DIPYDKI_dki_ak_voxel_count',
  'DIPYDKI_dki_fa_mean',
  'DIPYDKI_dki_fa_std',
  'DIPYDKI_dki_fa_median',
  'DIPYDKI_dki_fa_sum',
  'DIPYDKI_dki_fa_cv',
  'DIPYDKI_dki_fa_robust_mean',
  'DIPYDKI_dki_fa_robust_std',
  'DIPYDKI_dki_fa_robust_cv',
  'DIPYDKI_dki_fa_mad_median',
  'DIPYDKI_dki_fa_z_filtered_mean',
  'DIPYDKI_dki_fa_z_filtered_std',
  'DIPYDKI_dki_fa_iqr_filtered_mean',
  'DIPYDKI_dki_fa_iqr_filtered_std',
  'DIPYDKI_dki_fa_skewness',
  'DIPYDKI_dki_fa_excess_kurtosis',
  'DIPYDKI_dki_fa_percentile_5',
  'DIPYDKI_dki_fa_percentile_25',
  'DIPYDKI_dki_fa_percentile_75',
  'DIPYDKI_dki_fa_percentile_95',
  'DIPYDKI_dki_fa_coverage',
  'DIPYDKI_dki_fa_volume_mm3',
  'DIPYDKI_dki_fa_voxel_count',
  'DIPYDKI_dki_kfa_mean',
  'DIPYDKI_dki_kfa_std',
  'DIPYDKI_dki_kfa_median',
  'DIPYDKI_dki_kfa_sum',
  'DIPYDKI_dki_kfa_cv',
  'DIPYDKI_dki_kfa_robust_mean',
  'DIPYDKI_dki_kfa_robust_std',
  'DIPYDKI_dki_kfa_robust_cv',
  'DIPYDKI_dki_kfa_mad_median',
  'DIPYDKI_dki_kfa_z_filtered_mean',
  'DIPYDKI_dki_kfa_z_filtered_std',
  'DIPYDKI_dki_kfa_iqr_filtered_mean',
  'DIPYDKI_dki_kfa_iqr_filtered_std',
  'DIPYDKI_dki_kfa_skewness',
  'DIPYDKI_dki_kfa_excess_kurtosis',
  'DIPYDKI_dki_kfa_percentile_5',
  'DIPYDKI_dki_kfa_percentile_25',
  'DIPYDKI_dki_kfa_percentile_75',
  'DIPYDKI_dki_kfa_percentile_95',
  'DIPYDKI_dki_kfa_coverage',
  'DIPYDKI_dki_kfa_volume_mm3',
  'DIPYDKI_dki_kfa_voxel_count',
  'DIPYDKI_dki_linearity_mean',
  'DIPYDKI_dki_linearity_std',
  'DIPYDKI_dki_linearity_median',
  'DIPYDKI_dki_linearity_sum',
  'DIPYDKI_dki_linearity_cv',
  'DIPYDKI_dki_linearity_robust_mean',
  'DIPYDKI_dki_linearity_robust_std',
  'DIPYDKI_dki_linearity_robust_cv',
  'DIPYDKI_dki_linearity_mad_median',
  'DIPYDKI_dki_linearity_z_filtered_mean',
  'DIPYDKI_dki_linearity_z_filtered_std',
  'DIPYDKI_dki_linearity_iqr_filtered_mean',
  'DIPYDKI_dki_linearity_iqr_filtered_std',
  'DIPYDKI_dki_linearity_skewness',
  'DIPYDKI_dki_linearity_excess_kurtosis',
  'DIPYDKI_dki_linearity_percentile_5',
  'DIPYDKI_dki_linearity_percentile_25',
  'DIPYDKI_dki_linearity_percentile_75',
  'DIPYDKI_dki_linearity_percentile_95',
  'DIPYDKI_dki_linearity_coverage',
  'DIPYDKI_dki_linearity_volume_mm3',
  'DIPYDKI_dki_linearity_voxel_count',
  'DIPYDKI_dki_md_mean',
  'DIPYDKI_dki_md_std',
  'DIPYDKI_dki_md_median',
  'DIPYDKI_dki_md_sum',
  'DIPYDKI_dki_md_cv',
  'DIPYDKI_dki_md_robust_mean',
  'DIPYDKI_dki_md_robust_std',
  'DIPYDKI_dki_md_robust_cv',
  'DIPYDKI_dki_md_mad_median',
  'DIPYDKI_dki_md_z_filtered_mean',
  'DIPYDKI_dki_md_z_filtered_std',
  'DIPYDKI_dki_md_iqr_filtered_mean',
  'DIPYDKI_dki_md_iqr_filtered_std',
  'DIPYDKI_dki_md_skewness',
  'DIPYDKI_dki_md_excess_kurtosis',
  'DIPYDKI_dki_md_percentile_5',
  'DIPYDKI_dki_md_percentile_25',
  'DIPYDKI_dki_md_percentile_75',
  'DIPYDKI_dki_md_percentile_95',
  'DIPYDKI_dki_md_coverage',
  'DIPYDKI_dki_md_volume_mm3',
  'DIPYDKI_dki_md_voxel_count',
  'DIPYDKI_dki_mk_mean',
  'DIPYDKI_dki_mk_std',
  'DIPYDKI_dki_mk_median',
  'DIPYDKI_dki_mk_sum',
  'DIPYDKI_dki_mk_cv',
  'DIPYDKI_dki_mk_robust_mean',
  'DIPYDKI_dki_mk_robust_std',
  'DIPYDKI_dki_mk_robust_cv',
  'DIPYDKI_dki_mk_mad_median',
  'DIPYDKI_dki_mk_z_filtered_mean',
  'DIPYDKI_dki_mk_z_filtered_std',
  'DIPYDKI_dki_mk_iqr_filtered_mean',
  'DIPYDKI_dki_mk_iqr_filtered_std',
  'DIPYDKI_dki_mk_skewness',
  'DIPYDKI_dki_mk_excess_kurtosis',
  'DIPYDKI_dki_mk_percentile_5',
  'DIPYDKI_dki_mk_percentile_25',
  'DIPYDKI_dki_mk_percentile_75',
  'DIPYDKI_dki_mk_percentile_95',
  'DIPYDKI_dki_mk_coverage',
  'DIPYDKI_dki_mk_volume_mm3',
  'DIPYDKI_dki_mk_voxel_count',
  'DIPYDKI_dki_mkt_mean',
  'DIPYDKI_dki_mkt_std',
  'DIPYDKI_dki_mkt_median',
  'DIPYDKI_dki_mkt_sum',
  'DIPYDKI_dki_mkt_cv',
  'DIPYDKI_dki_mkt_robust_mean',
  'DIPYDKI_dki_mkt_robust_std',
  'DIPYDKI_dki_mkt_robust_cv',
  'DIPYDKI_dki_mkt_mad_median',
  'DIPYDKI_dki_mkt_z_filtered_mean',
  'DIPYDKI_dki_mkt_z_filtered_std',
  'DIPYDKI_dki_mkt_iqr_filtered_mean',
  'DIPYDKI_dki_mkt_iqr_filtered_std',
  'DIPYDKI_dki_mkt_skewness',
  'DIPYDKI_dki_mkt_excess_kurtosis',
  'DIPYDKI_dki_mkt_percentile_5',
  'DIPYDKI_dki_mkt_percentile_25',
  'DIPYDKI_dki_mkt_percentile_75',
  'DIPYDKI_dki_mkt_percentile_95',
  'DIPYDKI_dki_mkt_coverage',
  'DIPYDKI_dki_mkt_volume_mm3',
  'DIPYDKI_dki_mkt_voxel_count',
  'DIPYDKI_dki_planarity_mean',
  'DIPYDKI_dki_planarity_std',
  'DIPYDKI_dki_planarity_median',
  'DIPYDKI_dki_planarity_sum',
  'DIPYDKI_dki_planarity_cv',
  'DIPYDKI_dki_planarity_robust_mean',
  'DIPYDKI_dki_planarity_robust_std',
  'DIPYDKI_dki_planarity_robust_cv',
  'DIPYDKI_dki_planarity_mad_median',
  'DIPYDKI_dki_planarity_z_filtered_mean',
  'DIPYDKI_dki_planarity_z_filtered_std',
  'DIPYDKI_dki_planarity_iqr_filtered_mean',
  'DIPYDKI_dki_planarity_iqr_filtered_std',
  'DIPYDKI_dki_planarity_skewness',
  'DIPYDKI_dki_planarity_excess_kurtosis',
  'DIPYDKI_dki_planarity_percentile_5',
  'DIPYDKI_dki_planarity_percentile_25',
  'DIPYDKI_dki_planarity_percentile_75',
  'DIPYDKI_dki_planarity_percentile_95',
  'DIPYDKI_dki_planarity_coverage',
  'DIPYDKI_dki_planarity_volume_mm3',
  'DIPYDKI_dki_planarity_voxel_count',
  'DIPYDKI_dki_rd_mean',
  'DIPYDKI_dki_rd_std',
  'DIPYDKI_dki_rd_median',
  'DIPYDKI_dki_rd_sum',
  'DIPYDKI_dki_rd_cv',
  'DIPYDKI_dki_rd_robust_mean',
  'DIPYDKI_dki_rd_robust_std',
  'DIPYDKI_dki_rd_robust_cv',
  'DIPYDKI_dki_rd_mad_median',
  'DIPYDKI_dki_rd_z_filtered_mean',
  'DIPYDKI_dki_rd_z_filtered_std',
  'DIPYDKI_dki_rd_iqr_filtered_mean',
  'DIPYDKI_dki_rd_iqr_filtered_std',
  'DIPYDKI_dki_rd_skewness',
  'DIPYDKI_dki_rd_excess_kurtosis',
  'DIPYDKI_dki_rd_percentile_5',
  'DIPYDKI_dki_rd_percentile_25',
  'DIPYDKI_dki_rd_percentile_75',
  'DIPYDKI_dki_rd_percentile_95',
  'DIPYDKI_dki_rd_coverage',
  'DIPYDKI_dki_rd_volume_mm3',
  'DIPYDKI_dki_rd_voxel_count',
  'DIPYDKI_dki_rk_mean',
  'DIPYDKI_dki_rk_std',
  'DIPYDKI_dki_rk_median',
  'DIPYDKI_dki_rk_sum',
  'DIPYDKI_dki_rk_cv',
  'DIPYDKI_dki_rk_robust_mean',
  'DIPYDKI_dki_rk_robust_std',
  'DIPYDKI_dki_rk_robust_cv',
  'DIPYDKI_dki_rk_mad_median',
  'DIPYDKI_dki_rk_z_filtered_mean',
  'DIPYDKI_dki_rk_z_filtered_std',
  'DIPYDKI_dki_rk_iqr_filtered_mean',
  'DIPYDKI_dki_rk_iqr_filtered_std',
  'DIPYDKI_dki_rk_skewness',
  'DIPYDKI_dki_rk_excess_kurtosis',
  'DIPYDKI_dki_rk_percentile_5',
  'DIPYDKI_dki_rk_percentile_25',
  'DIPYDKI_dki_rk_percentile_75',
  'DIPYDKI_dki_rk_percentile_95',
  'DIPYDKI_dki_rk_coverage',
  'DIPYDKI_dki_rk_volume_mm3',
  'DIPYDKI_dki_rk_voxel_count',
  'DIPYDKI_dki_sphericity_mean',
  'DIPYDKI_dki_sphericity_std',
  'DIPYDKI_dki_sphericity_median',
  'DIPYDKI_dki_sphericity_sum',
  'DIPYDKI_dki_sphericity_cv',
  'DIPYDKI_dki_sphericity_robust_mean',
  'DIPYDKI_dki_sphericity_robust_std',
  'DIPYDKI_dki_sphericity_robust_cv',
  'DIPYDKI_dki_sphericity_mad_median',
  'DIPYDKI_dki_sphericity_z_filtered_mean',
  'DIPYDKI_dki_sphericity_z_filtered_std',
  'DIPYDKI_dki_sphericity_iqr_filtered_mean',
  'DIPYDKI_dki_sphericity_iqr_filtered_std',
  'DIPYDKI_dki_sphericity_skewness',
  'DIPYDKI_dki_sphericity_excess_kurtosis',
  'DIPYDKI_dki_sphericity_percentile_5',
  'DIPYDKI_dki_sphericity_percentile_25',
  'DIPYDKI_dki_sphericity_percentile_75',
  'DIPYDKI_dki_sphericity_percentile_95',
  'DIPYDKI_dki_sphericity_coverage',
  'DIPYDKI_dki_sphericity_volume_mm3',
  'DIPYDKI_dki_sphericity_voxel_count',
  'DIPYDKI_dkimicro_ad_mean',
  'DIPYDKI_dkimicro_ad_std',
  'DIPYDKI_dkimicro_ad_median',
  'DIPYDKI_dkimicro_ad_sum',
  'DIPYDKI_dkimicro_ad_cv',
  'DIPYDKI_dkimicro_ad_robust_mean',
  'DIPYDKI_dkimicro_ad_robust_std',
  'DIPYDKI_dkimicro_ad_robust_cv',
  'DIPYDKI_dkimicro_ad_mad_median',
  'DIPYDKI_dkimicro_ad_z_filtered_mean',
  'DIPYDKI_dkimicro_ad_z_filtered_std',
  'DIPYDKI_dkimicro_ad_iqr_filtered_mean',
  'DIPYDKI_dkimicro_ad_iqr_filtered_std',
  'DIPYDKI_dkimicro_ad_skewness',
  'DIPYDKI_dkimicro_ad_excess_kurtosis',
  'DIPYDKI_dkimicro_ad_percentile_5',
  'DIPYDKI_dkimicro_ad_percentile_25',
  'DIPYDKI_dkimicro_ad_percentile_75',
  'DIPYDKI_dkimicro_ad_percentile_95',
  'DIPYDKI_dkimicro_ad_coverage',
  'DIPYDKI_dkimicro_ad_volume_mm3',
  'DIPYDKI_dkimicro_ad_voxel_count',
  'DIPYDKI_dkimicro_ade_mean',
  'DIPYDKI_dkimicro_ade_std',
  'DIPYDKI_dkimicro_ade_median',
  'DIPYDKI_dkimicro_ade_sum',
  'DIPYDKI_dkimicro_ade_cv',
  'DIPYDKI_dkimicro_ade_robust_mean',
  'DIPYDKI_dkimicro_ade_robust_std',
  'DIPYDKI_dkimicro_ade_robust_cv',
  'DIPYDKI_dkimicro_ade_mad_median',
  'DIPYDKI_dkimicro_ade_z_filtered_mean',
  'DIPYDKI_dkimicro_ade_z_filtered_std',
  'DIPYDKI_dkimicro_ade_iqr_filtered_mean',
  'DIPYDKI_dkimicro_ade_iqr_filtered_std',
  'DIPYDKI_dkimicro_ade_skewness',
  'DIPYDKI_dkimicro_ade_excess_kurtosis',
  'DIPYDKI_dkimicro_ade_percentile_5',
  'DIPYDKI_dkimicro_ade_percentile_25',
  'DIPYDKI_dkimicro_ade_percentile_75',
  'DIPYDKI_dkimicro_ade_percentile_95',
  'DIPYDKI_dkimicro_ade_coverage',
  'DIPYDKI_dkimicro_ade_volume_mm3',
  'DIPYDKI_dkimicro_ade_voxel_count',
  'DIPYDKI_dkimicro_awf_mean',
  'DIPYDKI_dkimicro_awf_std',
  'DIPYDKI_dkimicro_awf_median',
  'DIPYDKI_dkimicro_awf_sum',
  'DIPYDKI_dkimicro_awf_cv',
  'DIPYDKI_dkimicro_awf_robust_mean',
  'DIPYDKI_dkimicro_awf_robust_std',
  'DIPYDKI_dkimicro_awf_robust_cv',
  'DIPYDKI_dkimicro_awf_mad_median',
  'DIPYDKI_dkimicro_awf_z_filtered_mean',
  'DIPYDKI_dkimicro_awf_z_filtered_std',
  'DIPYDKI_dkimicro_awf_iqr_filtered_mean',
  'DIPYDKI_dkimicro_awf_iqr_filtered_std',
  'DIPYDKI_dkimicro_awf_skewness',
  'DIPYDKI_dkimicro_awf_excess_kurtosis',
  'DIPYDKI_dkimicro_awf_percentile_5',